# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orchestra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orchestra

end

target 'Orchestra WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orchestra WatchKit App

end

target 'Orchestra WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orchestra WatchKit Extension

end
