# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0'

target 'Orchestra' do
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  # Utils
  #pod 'Kingfisher' # https://github.com/onevcat/Kingfisher
  pod 'ReachabilitySwift' # https://github.com/ashleymills/Reachability.swift
  pod 'RxSwift'
  pod 'RxCocoa'
  
  #Permissions
  pod 'SPPermissions/Notification' # https://github.com/ivanvorobei/SPPermissions
  pod 'SPPermissions/Bluetooth'
  pod 'SPPermissions/PhotoLibrary'
  pod 'SPPermissions/Location'

  # REST
  pod 'Alamofire' # https://github.com/Alamofire/Alamofire
  pod 'RxAlamofire' # https://github.com/RxSwiftCommunity/RxAlamofire
  pod 'ObjectMapper' # https://github.com/tristanhimmelman/ObjectMapper

  # Material
  pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner.git', :branch => 'master'
  pod 'MRProgress'
  pod 'Floaty', '~> 4.2.0'
  pod 'CHIPageControl', '~> 0.1.3'
  pod 'FittedSheets'
  pod 'NewPopMenu', '~> 2.0'
end

target 'Orchestra WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orchestra WatchKit App

end

target 'Orchestra WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # REST
  pod 'Alamofire'

end
