fastlane_require "dotenv"

before_all do
  Dotenv.load ".env.secret"
end

default_platform(:ios)

lane :create_app do
	create_app_online  # produce
end

platform :watchos do
  desc "Release testflight watch"
  lane :watch do
    match(type: "appstore", readonly: is_ci)

    # Use gym to archive your app
    gym(
      silent: true,
      output_directory: "./fastlane/builds",
      # xcargs: "-allowProvisioningUpdates",
      scheme: "Orchestra WatchKit App"
    )
  end
end

platform :ios do
  before_all do
  	Dotenv.load ".env.ios"
  end

  desc "Sync signing"
  lane :signing do
    sync_code_signing # match

    mapping = Actions.lanecontext[
    	SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
     profile_name:  mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app # gym
  end

  desc "Release binary"
  lane :release_appstore do
  	ensure_git_status_clean
  	ensure_git_branch

    build
    upload_to_app_store

    reset_git_repo
  end

  desc "Build & Deploy to TestFlight"
  lane :release_testflight do |options|

    # run this : chmod +x ./scripts/upgrade_buildNumber.sh
    sh("../scripts/upgrade_buildNumber.sh", options[:version])
    
    # Update Info plist Bundle ID
    update_app_identifier(
      xcodeproj: "Orchestra.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Orchestra/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: ENV["PRODUCE_APP_IDENTIFIER"] # The App Identifier
    )

    # Update Info plist AppName
    update_info_plist( # Change the Display Name of your app
      plist_path: "./Orchestra/Info.plist",
      display_name: ENV["PRODUCE_APP_NAME"]
    )

    # download and use certificate
    match(type: "appstore", readonly: is_ci)

    # Use gym to archive your app
    #gym(
    #  silent: true,
    #  output_directory: "./fastlane/builds",
      # xcargs: "-allowProvisioningUpdates",
    #  scheme: ENV["SCHEME"]
    #)

    build_app(
      scheme: ENV["SCHEME"],
      output_directory: "./fastlane/builds",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "com.nrv.orchestra" => "match AppStore com.nrv.orchestra",
          "com.nrv.orchestra.watchkitapp" => "match AppStore com.nrv.orchestra.watchkitapp",
          "com.nrv.orchestra.watchkitapp.watchkitextension" => "com.nrv.orchestra.watchkitapp.watchkitextension"
        }
      }
    )

    # Use pilot to upload your app to testflight
    pilot(
      app_identifier: ENV["PRODUCE_APP_IDENTIFIER"],
      distribute_external: false,
    )
  end


  desc "Livraison TestFlight"
  lane :testflight_pilot do
     # Use gym to archive your app
    gym(
      silent: true,
      output_directory: "./fastlane/builds",
      # xcargs: "-allowProvisioningUpdates",
      scheme: ENV["SCHEME"]
    )

    pilot(
      app_identifier: ENV["PRODUCE_APP_IDENTIFIER"],
      ipa: "./fastlane/builds/Orchestra.ipa",
      distribute_external: false,
    )
  end

  desc "clean project"
  lane :clean do |options|
    sh("rm", "-rf", "./fastlane/builds/**.zip")
    #sh "rm -rf builds/carto-sdk-ios.xcarchive"
    sh("rm", "-rf", "./fastlane/builds/**.ipa")
    #sh "rm -rf builds/carto-sdk-ios.app.dSYM.zip"
  end
end
